### PR TITLE
WIP: Wrap C code with Cython instead of manually written C-API

### PR DESCRIPTION
**Pull request by SpotlightKid**
* Add Cython declaration file (`_jack_mixer.pxd`) for `jack_mixer.h` and `scale.h`.
* Add Cython implementation file (`_jack_mixer.pyx`), which defines `Scale,`Mixer`,`Channel`and`OutputCHannel` extensions classes.
* Add `setup.py` file, which compiles Cython code to `_jack_mixer` extension module, which can act as a drop-in replacement for the `jack_mixer_c` extension module.
* Adapt git ignore file to ignore Cython-generated C source code and distutils/setuptools artifacts.

Work in progress!

~Some recent changes to C functions might not be wrapped yet.~

### CODE REVIEW

**Comment by SpotlightKid** [comment]
The motivation for this is that I noticed, when I worked on the C code, trying out things for FR #1, I found it quite cumbersome to update the wrapper code in jack_mixer_c.c and hard to get right.

I think the Cython is much easier to understand and work on, it has less than half the number of lines and is easier to compile with the provided `setup.py`. It does introduce the additional compile time dependency on Cython, though. The setup.py currently does not do everything the autoconf stuff does, but I hope to improve that.

**Comment by SpotlightKid** [comment]
To try out:

```console
$ python setup.py build_ext --inplace
$ ./jack_mixer.py
```

**Comment by SpotlightKid** [comment]
Updated the Cython binding to wrap the `output_channel_set_in_prefader` function. They should now provide everything the old bindings do.

**Comment by SpotlightKid** [comment]
Update binding to changes in C API in 8674b409e0a2460fbd92455afe92335c516bffdf and 0bab4b8cf80f7c29fb2cde5b2a10fc5ce7034b25.

Also wrapped `channel_set_midi_cc_balance_picked_up` and `channel_set_midi_cc_volume_picked_up` and inserted appropriate calls to them in `channel.py`. This fixes MIDI pickup mode, which was not working with the Cython bindings before.

IMHO calling these functions in the bindings in `Channel.set_balance` and `Channel.set_volume` is at the wrong abstraction level.

**Comment by dsheeler** [comment]
How should the `channel_set_midi_cc_volume_picked_up` stuff work?  I'm not sure I see the issue

**Comment by SpotlightKid** [comment]
The current bindings in `jack_mixer_c.c` call `channel_set_midi_cc_balance_picked_up` and `channel_set_midi_cc_balance_picked_up` in the `Channel.balance` and `Channel.volume` property setter methods. This leaves no way for Python code to set the channel balance or volume without resetting the picked-up status. IMHO, it should be the responsibility of the Python layer to reset the picked-up status when it needs to (i.e. a balance/volume change was triggered via the UI), not the bindings, which IMO should only wrap the C functions or make them more convenient to access from Python (e.g. with properties), but not change/enhance what they do.

**Comment by dsheeler** [comment]
I think I was planning on doing it more like you are suggesting, like that's why I implemented some C that "wasn't necessary".  I need a little time to think this through, but I think I agree with what you're saying.

**Comment by SpotlightKid** [comment]
I did some fairly extensive clean-up work by removing the autoconf / automake stuff in this branch and switching the building and installation to a Python setuptools-based approach. This means that:

* You build a source distribution with `python setup.py bdist` (creates a TGZ in `dist`).
* You install from the repo or an unpacked source distribution with `pip install .`
  
  * This installs the Python files as a package in Python's `site-packages` directory instead of
    `<prefix>/share/jack_mixer`.
  * This installs a starter script for `jack_mixer` in `<prefix>/bin`, which would potentially also work on non-Linux systems (the rest of jack_mixer probably doesn't yet) without the need for a symlink to `jack_mixer.py`.
  * This also allows to install jack_mixer in a Python virtual environment.

* You can build a binary wheel with `python setup.py bdist_wheel` (but that's really only useful on Windows, since on Linux you'd have compatibility issues with glib etc.)

* jack_mixer could even be uploaded to [PyPI](https://pypi.org) and install from there with `pip install jack_mixer`.

At some point I would like to further restructure the repo layout and move the C sources and the Python files into their own separate subdirectories:

* This would allows to do `pip install -e .`, i.e.an  [editable install](https://packaging.python.org/guides/distributing-packages-using-setuptools/#working-in-development-mode), since the Python source files now form a valid Python package directory in the repo.
* It makes the repo much more clearly laid out.
* The `setup.py` file would become more sane. :)

**Notes / Bugs:**

* There might be still problems with the installation of the icons and the desktop file. I need to look into that.
* There is currently no support for building and installing `jack-mix_box`. I'm investigating using `meson` for that, for the installation of the data files, and integrating that with the setuptools based setup, so that the `setup.py` file can be simplified.

**Comment by SpotlightKid** [comment]
Closing this in favour of #106.

**Pull request closed without merging**
